### PR TITLE
Tweaks on the MutCursorRootedVec API from @steffahn

### PR DESCRIPTION
**Pull request by luketpeterson**
Continuation of https://github.com/luketpeterson/mutcursor/pull/4

### CODE REVIEW

**Comment by luketpeterson** [comment]
Comment copied from already-merged PR:

@steffahn Apologies it took me so long to review this; I have been under the weather during the last week.

Anyway, I tried to make some examples to clarify when it's appropriate to use the "ordinary" methods vs. the "_twostep" methods. And it's a little unclear to me.

First I tried to make an example using a container (Vec) as RootT, but I ran into the issue that the Vec<T> doesn't implement DerefMut<Target=T>

I ended up removing the DerefMut bound and the double-reference from the API in order to use it the way I imagined. But it seems perhaps I misunderstood your intent and traded flexibility in one dimension for flexibility in another. (or made something unsound in a subtle way!)

My changes are here: https://github.com/luketpeterson/mutcursor/tree/lp_remove_deref_bound_in_fs_api along with a usage example

Thanks for your work on this! I hope we can make something that's broadly useful to others.

**Comment by luketpeterson** [comment]
Ugh.  I realized I was misunderstanding `StableDeref` as a property of types on which it is implemented, when it more correctly should be understood as a property of the `Deref` / `DerefMut` impl.  Therefore my revisions to your API introduced a soundness hole.

**Comment by luketpeterson** [comment]
I have an alternative API that is closer to your original one, but I have still made some changes.  I want to spend the night thinking about it before I waste your time with a review.

**Comment by steffahn** [comment]
> First I tried to make an example using a container (Vec) as RootT, but I ran into the issue that the Vec doesn't implement DerefMut<Target=T>

The vec example works fine using my existing API if you're using `Vec<T>: Deref<Target = [T]>`, i.e.:
```rust
use mutcursor::MutCursorRootedVec;
let tree_vec = vec![TreeNode::new(5)];
let mut node_stack = MutCursorRootedVec::<'static, Vec<TreeNode>, TreeNode>::new(tree_vec);

// Begin traversal from the root
node_stack.advance_from_root_twostep(|v| Some(v), |v| v.get_mut(0));

// Traverse to the last node
while node_stack.advance(|node| node.traverse()) {}

assert_eq!(node_stack.top().unwrap().val, 0);
assert_eq!(node_stack.depth(), 6);

struct TreeNode {
    val: usize,
    next: Option<Box<TreeNode>>,
}
impl TreeNode {
    fn new(count: usize) -> Self {
        if count > 0 {
            Self {
                val: count,
                next: Some(Box::new(Self::new(count - 1))),
            }
        } else {
            Self { val: 0, next: None }
        }
    }
    fn traverse(&mut self) -> Option<&mut Self> {
        self.next.as_deref_mut()
    }
}
```

Note that this “`|v| Some(v)`” case is what this variant of the API could potentially make nicer by leaving out the `|v| Some(v)` part:
> then it’d be possible to instead leave out the first step instead, requiring `Root: DerefMut + StableDeref` and starting a `step_f` only from the target of that reference

(quoted from #4)

**Comment by luketpeterson** [comment]
The name of this branch is no longer appropriate as I reverted all substantive API changes.  But merging regardless as doc changes are still appropriate.

**Pull request merged**
